### ISSUE TITLE
parcellation scheme

### ISSUE THREAD

**Issue by rsanfeli** [DevelopmentalImagingMCRI/freesurfer_statsurf_display#5]
Hi! 
I really like this toolbox and I'd like to use it to visualize my results, however I don't want to project them (p-values, effect sizes etc.) on Desikan/Destrieux/Economo atlases. 

I used a sparse dimensionality reduction method and got components, which I'd also like to visualize results on. Thus, I tried to construct my own .annot file to then add this to all the functions of the toolbox (i.e., as an additional "case"). Here I run into the problem of the original files for the atlases (field "orig" in the colorable), which doesn't let me read the colortable. 

Do you know either how to solve this issue, or if there's another, smoother way to overcome this limitation?

Thanks a lot!!

**Comment by chrisadamsonmcri** [comment]
Hello.

So you have your own parcellation scheme and want to use it?

Perhaps if you attach the changes you made and send the annot file for the fsaverage surfaces that are in the toolbox, (the ones used to display the surfaces) then I can have a look.

Thanks for the message.

**Comment by rsanfeli** [comment]
Thanks a lot for your reply.

Yes, that's correct. I would both like to just display the parcels with different colors, and the stats (i.e., p-values and effect sizes). I reckon this would be possible with the toolbox if I'd convert my parcels in an annotation file, right? 

Attached a text file with explanations+code, and the .mat variable for the vectors. I hope it's clear, but please let me know if you need more details. 

Thank you very much for your support.

[Issue_statssurf_display.zip](https://github.com/DevelopmentalImagingMCRI/freesurfer_statsurf_display/files/5122189/Issue_statssurf_display.zip)

**Comment by chrisadamsonmcri** [comment]
So, here I try to explain my pipeline:

1. I constructed the components using fsaverage6 (found in the /subj folder of FreeSurfer), which has 40.962 vertices.

2. I have in total 18 components (i.e., parcels), but some of them are asymmetrical and have been zeroed out (1,10,13 an 18 for LH and 2,6,7). So in total 14 components for the left and 15 for the right hemisphere will be coloured, the rest of the brain should be gray. 

3. In the two attached files you'll see 14 and 15 unique values. Each of them should get a different colour, so that's my code (very sorry if it's not high-standard, I'm a clinical neuroscientist...)


Ok I get what you are trying to do and you are on the right track.
Firstly, the surfaces that I use in the toolbox are the 7th order spheres with 163842 vertices so you will need to resample your components onto that.
Secondly, per your code.

Use the annot files in the freesurfer_statsurf_display toolbox since they have the 163482 vertices you will need.

%% Load von Economo annot file
% I load this to get the colourtable (they look nicer than Desikan/Destrieux)
fs6 = 'myotheranalysesdirectory/freesurfer_statsurf_display/fsaverage_fs6/label/';
[verticesE, labelE, colortableE] = read_annotation([fs6,'rh.economo.annot']); %Economo colours 

they also have the correct number of vertices

ok what I would do is just select the number of "regions" you need, something like

colortable = colortableE;
numRegions = 16

colortable.struct_names = colortable.struct_names(1:numRegions + 1);
colortable.numEntries = numRegions + 1;
colortable.table = colortableE.table(1:numRegions + 1, :);

I chose the first numRegions + 1 but
as an aside, if you did want to select specific labels labels
colortable.struct_names = {'unknown','FA','FB','FC','FD','OA','OB','OC','PA','PB','PC','PD','TA','TB','TC','TD'}';

instead of doing this loop
t = [];
for i=1:size(colortable.struct_names,1)
   t = [t;colortableE.table(strcmp(colortableE.struct_names,colortable.struct_names{i,1}),:)];
end

do this
[~, LOC] = ismember(colortable.struct_names, colortableE.struct_names);
colortable.table = colortableE.table(LOC, :);


don't worry about the orig_tab it is ignored

ok to construct the label vectors all you need is this

labelL = colortable.table(NMF_total_lh + 1, 5);
labelR = colortable.table(NMF_total_rh + 1, 5);

then
freesurfer_write_annot(

colortable.table = t;
clear colortableE t i

rois_lh = unique(NMF_total_lh);
label = zeros(size(NMF_total_lh,1),1);
for i=2:size(rois_lh,1)
    label(NMF_total_lh==rois_lh(i),1) = colortable.table(i,5);
end
label(label==0,1) = colortable.table(1,5); % because the first one is grey

rois_rh = unique(NMF_total_rh);
labelR = zeros(size(NMF_total_rh,1),1);
for i=2:size(colortable.table,1)
    labelR(NMF_total_rh==rois_rh(i),1) = colortable.table(i,5);
end
labelR(labelR==0,1) = colortable.table(1,5); % because the first one is grey

clear rois_lh rois_rh

%% save annot files
save([fs6,'/lh.psc18.annot'],'colortable','vertices','label');
save([fs6,'/rh.psc18.annot'],'colortable','verticesR','labelR');

And here the problem: I can't save the .annot files because the orig file is missing and so the colourtable results an empty structure.

Use my freesurfer_write_annot(filename, vertices, label, structure, colortable) function and do this
freesurfer_write_annot([fs6,'/lh.psc18.annot'], verticesE, labelL, [], colortable);
freesurfer_write_annot([fs6,'/rh.psc18.annot'], verticesE, labelR, [], colortable);

Put the resulting output annot files into the fsaverage_fs6 directory in the freesurfer_statsurf_display directory. 
Run freesurfer_statsurf_fsrgb using 'psc18' as the seed scheme.

[freesurfer_write_annot.zip](https://github.com/DevelopmentalImagingMCRI/freesurfer_statsurf_display/files/5133813/freesurfer_write_annot.zip)

**Comment by rsanfeli** [comment]
Thank you very very much for this!!! With other small things it worked.
I will of course cite the toolbox on the paper--super nice!

ps: Dom (your ex colleague in Melbourne now living in Munich) says hi! :-)

Thanks again,
Rachele

**Comment by chrisadamsonmcri** [comment]
Thanks Rachele for the comments. I'm glad it worked for you.

Hi Dom!
